### PR TITLE
Add a link to Qt Node Editor

### PR DESCRIPTION
**Pull request by paceholder**
;-)

---
This change is [Reviewable](https://reviewable.io/reviews/chigraph/chigraph/74)

### CODE REVIEW

**Comment by russelltg** [comment]
Wow not sure now I forgot that...I'm embarrassed but thanks for noticing.

**Comment by russelltg** [comment]
Yeah so...I just rewrote a ton of git history to delete old files. I'll merge manually. 

I should have merged this first :smile:.

**Comment by russelltg** [comment]
https://github.com/chigraph/chigraph/commit/bbb16137d0e4bdb916f8ec49348db821f204878a

**Comment by paceholder** [comment]
> Wow not sure now I forgot that...I'm embarrassed but thanks for noticing.

Dot be embarrassed -- not a big deal ;) I juts thought it would be fair to have cross-referencing

Thanks

**Pull request closed without merging**
